[package]
name = "recipe"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1.0", features = ["sqlite"] }
diesel_migrations = "2.1.0"

# Bundle SQLite3 with the code so it compiles on Windows
libsqlite3-sys = { version = "*", features = [ "bundled" ] }